### ISSUE TITLE
Wrong length for curly apostrophe

### ISSUE THREAD

**Issue by jgm** [jgm/doclayout#5]
```
Prelude Text.DocLayout Data.List> literal "a’s"
Text 2 "a\8217s"
```
Should be length 3.  I found this after noting a bunch of wrapping-related test failures in pandoc from the new doclayout release.

@Xitian9 can you see the problem?  I believe this is due to your changes in real length calculation code.

**Comment by jgm** [comment]
Also with double quotes
```
Prelude Text.DocLayout Data.List> literal "a“b"
Text 2 "a\8220b"
```

**Comment by Xitian9** [comment]
Let me look into it.

**Comment by Xitian9** [comment]
Good catch. It looks like I mistyped the end of the ‘zero width joiners and directional markers’ block. which should be `\x2010`, not `\x2030` (they are next to each other on my keyboard). I'll issue a fix.

**Comment by Xitian9** [comment]
It would be good to come up with a more comprehensive test suite to be able to catch these things. There are a load of extra characters sprinkled throughout unicode that should be zero-width, and I certainly haven't gotten all of them.

Also, ambiguous characters technically should be either width 1 or 2 depending on what they're surrounded by…
